### ISSUE TITLE
Fix accessibility issues by updating the govuk_tech_docs gem to 2.2.0 [before 31 March]

### ISSUE THREAD

**Issue by 36degrees** [alphagov/govuk-frontend-docs#104]
## What

First, update the govuk_tech_docs gem from 2.1.0 to 2.2.0.

<details>
<summary>Change log</summary> 

> ## 2.2.0
> 
> ### Accessibility Fixes
> 
> - [#205: Improve table of contents accessibility](https://github.com/alphagov/tech-docs-gem/pull/205)
> - [#209: Some search and keyboard navigation updates](https://github.com/alphagov/tech-docs-gem/pull/209)
> - [#210: Stop linking images to new tabs](https://github.com/alphagov/tech-docs-gem/pull/210)
> - [#214: Implement row level table headings to allow accessible tables with row headings](https://github.com/alphagov/tech-docs-gem/pull/214)
> - [#215: Add tabindex and focus states to code blocks](https://github.com/alphagov/tech-docs-gem/pull/215)
> 
> ### Docs
> 
> - [#206: Remove tdt docs content from readme file](https://github.com/alphagov/tech-docs-gem/pull/206)
> 
> ## 2.1.1
> 
> ### Fixes
> 
> We’ve made fixes in the following pull requests:
> 
> - [#199: Fix page expiry box link colours (hover and focus) ](https://github.com/alphagov/tech-docs-gem/pull/199)
> 
> ### Ruby version bump
> 
> We've updated the Ruby version supported:
> 
> - [#201: Bump ruby to 2.7.2](https://github.com/alphagov/tech-docs-gem/pull/201)
</details>

Then identify and fix any tables which require row level headers.

There is a single table in [migrating from legacy products](https://frontend.design-system.service.gov.uk/migrating-from-legacy-products/#1-uninstall), and multiple tables in the Sass API reference docs.

## Why

Version 2.2.0 of the tech docs gem is now live and incorporates fixes to a number of accessibility issues in the technical documentation template which are referenced in our accessibility statement:

- Some tables in content do not have column row headers when needed.
- Users cannot tab to code examples to scroll them using the keyboard.
- The search field and the ‘Hide table of contents’ button are not placed logically in the focus order.
- Users can focus elements that are hidden visually behind other content, for example when using the search field.
- Images link to a new tab without telling users, and do not have link text.

## Done when

- [x] Gem updated
- [ ] Tables include row headers where required
- [ ] Verified that the issues listed in the accessibility statement are fixed (see [guidance](https://docs.google.com/document/d/1QlTbEV6xyUsc5Tb94Iw5GrnifCuzaZB8TDIKmV5QDCs/edit#heading=h.w7nppph95a2s))

**Comment by EoinShaughnessy** [comment]
Have raised PR for Gemfile update: https://github.com/alphagov/govuk-frontend-docs/pull/106

**Comment by EoinShaughnessy** [comment]
Have raised PR for fix to table in [migrating from legacy products](https://frontend.design-system.service.gov.uk/migrating-from-legacy-products/#1-uninstall): https://github.com/alphagov/govuk-frontend-docs/pull/107
