### ISSUE TITLE
Class missing from CSS (GDS Components)

### ISSUE THREAD

**Issue by brenda-campbellSFDC** [alphagov/govuk-frontend-docs#140]
HI,

Where can I find the class that is part of CSS i.e. govuk-js-header-toggle (included in the govHeader component).  See the HTML provide for 'Header with service name and navigation' - [https://design-system.service.gov.uk/components/header/](url)

Also center-buttons, navigation-buttons, right-buttons, left-buttons from Navigation buttons.

I've tried to generate the CSS file from the SCSS files available but some of the classes are missing.

**Comment by brenda-campbellSFDC** [comment]
Hi @vanitabarrett - thanks very much for your response. Would it be possible to share a sample of the JavaScript file for the header so I can understand how it is used. Ideally would like to have all the styling in a CSS file. At the moment, trying to create a component and it does not work as expected on mobile.

**Comment by vanitabarrett** [comment]
Hi @brenda-campbellSFDC - yes of course. For future reference, all the code behind any components in the Design System can be found in this Github repo: https://github.com/alphagov/govuk-frontend

For example, the Javascript for the header component can be found here: https://github.com/alphagov/govuk-frontend/blob/main/src/govuk/components/header/header.js

Also, sorry if my previous message was unclear. The `govuk-js-header-toggle` is used in the JavaScript file for targeting that specific element, e.g: using `document.querySelector` - not to apply styling. That element also has a `govuk-header__menu-button` class which is used in the CSS to apply styling to that element (note there is no '-js-' in this class name, suggesting it is used within CSS)

**Comment by vanitabarrett** [comment]
Hi @brenda-campbellSFDC - we've not heard back from you recently, so I'm going to close this issue for now. If you require more support from the GOV.UK Design System team or have any more questions for us, you can send an email to govuk-design-system-support@digital.cabinet-office.gov.uk and we'll get back to you as soon as possible.

**Comment by brenda-campbellSFDC** [comment]
Thanks @vanitabarrett  - the information you provided was very helpful
