### ISSUE TITLE
Update Internet Explorer documentation

### ISSUE THREAD

**Issue by vanitabarrett** [alphagov/govuk-frontend-docs#188]
## What
Update any documentation in the GOV.UK Frontend Docs repo that references our browser support, e.g: we have a section on how to 'Support Internet Explorer 8' and some Sass docs including `$govuk-is-ie8`. We should consider how our changes to browser support affect these docs.

## Why
We are changing our browser support, so should make sure our documentation is updated. See our [browser proposal](https://github.com/alphagov/govuk-frontend/discussions/2607) for more details.

## Depends On
Work to figure out how we maintain 2 documentation sites in parallel (v4 and v5+)

## Who needs to work on this
Tech writer; Developers

## Who needs to review this
Developers

## Done when

- [ ] This is linked to the content changes underway for v4/v5 amendments. Those changes will complete the work outlined in this card as well.

**Comment by claireashworth** [comment]
IE8 content changes are being tracked in #311 
I'm closing this issue as it's impacting a Design System epic.
