### ISSUE TITLE
Define and make required changes to v4.0.0 documentation

### ISSUE THREAD

**Issue by vanitabarrett** [alphagov/govuk-frontend-docs#189]
## What
Parallel documentation for versions 4 and 5 of the Design System were planned in #3549 and Prepared in #2186. This is to list the changes needed to update our documentation to v5.

## Why
See our [browser proposal](https://github.com/alphagov/govuk-frontend/discussions/2607) for more details.

## Who needs to work on this
Developers; Designers; Tech Writer

## Who needs to review this
Developers; Designers; Tech Writer

## Done when

- [x] We've investigated and decided on an approach to maintaining v4 documentation alongside the latest stuff
- [ ] TBC cards for implementation

**Comment by claireashworth** [comment]
Closed because this is for the v4/v5 content changes to the design system site and needs to be moved to the correct repo.
