### ISSUE TITLE
Improvements to component initialisation and CSP documentation

### ISSUE THREAD

**Issue by vanitabarrett** [alphagov/govuk-frontend-docs#203]
We currently advise people to [initialise our JavaScript in an inline script tag](https://frontend.design-system.service.gov.uk/importing-css-assets-and-javascript/#add-the-javascript-file-to-your-html).

The new approach to passing translations in via JavaScript will also talk about inline script tags.

Our CSP documentation says that you can add a hash to allow any inline scripts. However, the hash we provide is only [a hash for the `js-enabled` script'](https://github.com/alphagov/govuk-frontend-docs/issues/68). We don't talk about any of the other inline scripts we recommend using.

## Who needs to know about this
Developers; Tech Writer

## Done when

- [x] CSP documentation references all inline scripts, rather than assuming the `js-enabled` script is the only one
- [x] There is clear documentation to help users who have a CSP and have other inline scripts

**Comment by stevenjmesser** [comment]
@colinrotherham Will this issue be outdated once we start using `type="module"`?

**Comment by stevenjmesser** [comment]
Potentially closed once https://github.com/alphagov/govuk-frontend-docs/issues/308 is done.

**Comment by colinrotherham** [comment]
@stevenjmesser Ah it's been duplicated as the 3rd tasklist item in:

>[The SHA hash for the snippet](https://frontend.design-system.service.gov.uk/importing-css-assets-and-javascript/#use-a-hash-to-unblock-inline-javascript) has been updated in the Frontend docs

* https://github.com/alphagov/govuk-frontend/issues/3508

**Comment by colinrotherham** [comment]
Closing as the [tasks are duplicated](https://github.com/alphagov/govuk-frontend-docs/issues/203#issuecomment-1564341233)
