### ISSUE TITLE
Update docs to identify compatibility mode information and associated variables, mixins and settings as unavailable from 5.0

### ISSUE THREAD

**Issue by owenatgov** [alphagov/govuk-frontend-docs#207]
## What
Identify settings, variables and any other content pertaining to compatibility mode and the support of legacy design systems and identify it as deprecated and no longer available in 5.0.

## Why
We are removing compatibility mode in 5.0 and should reflect this in our documentation.

Part of https://github.com/alphagov/govuk-frontend/issues/2769

## Who needs to work on this
Developers, Tech writers

## Done when

- [x] Identify settings, variables and mixins notes in the epic from the [Sass API reference](https://frontend.design-system.service.gov.uk/sass-api-reference/#sass-api-reference) and note that they aren't available in 5.0
- [x] Add a note to the [Use with our old frameworks or colours page](https://frontend.design-system.service.gov.uk/compatibility-mode/) that we don't support this in 5.0
- [x] Add a note to the [Migrate from our old frameworks page](https://frontend.design-system.service.gov.uk/migrating-from-legacy-products/) that we no longer support compatibility mode as of 5.0

**Comment by owenatgov** [comment]
We think this work could be investigated and completed as part of https://github.com/alphagov/govuk-frontend/issues/3483 as compatibility mode and the docs surrounding it are an explicit feature that **will** be in v4 but **won't** be in v5.

**Comment by 36degrees** [comment]
@owenatgov we've now released v5 – is this still useful in terms of communicating the change? If not, can we close this?

**Comment by owenatgov** [comment]
We can indeed close this. This was superseded by work to split the v4 and v5 docs, which is now done.
