### ISSUE TITLE
Finalise titles and URLs for new documentation for v4.4.0

### ISSUE THREAD

**Issue by 36degrees** [alphagov/govuk-frontend-docs#214]
## What

- Finalise titles and URLs for new pages and record in [the draft doc](https://docs.google.com/document/d/1ztulyMp_pxi-uJimWrKQtnfSjdDDIN4Qr9rKmAHWO_0/edit#)
- Update the changelog to point to the expected final URLs for the documentation

## Why

Because we need to be able to point to the new documentation before it's published, we need to know what the URLs will be for the new pages.

We tend to try and keep the title and the URL (the 'slug') in sync, so finalising the URLs also means finalising the titles for each page.

## Who needs to know about this

Tech writer, developer

## Done when

- [x] We're happy with the titles and URLs for the new pages introduced relating to v4.4.0
- [x] The changelog has been updated to use the agreed URLs

**Comment by claireashworth** [comment]
Need one more title confirmation, but have written what I think the URLs will be.

**Comment by claireashworth** [comment]
Final title agreed.
