### ISSUE TITLE
Re: 'Import JavaScript'

### ISSUE THREAD

**Issue by aisb459** [alphagov/govuk-frontend-docs#296]
Problem with 'Import  JavaScript' (https://frontend.design-system.service.gov.uk/importing-css-assets-and-javascript/)

I am trying to use Govuk-Frontend npm package in Oracle JET application and I am getting the following error when I try to invoke 
initAll() function.

**Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'initAll')**

**Comment by owenatgov** [comment]
Hi @aisb459. We've also received a zendesk ticket from you on this issue. I'm going to close this github issue in favour of handling the problem in zendesk/via email.
