### ISSUE TITLE
Re: 'Get started'

### ISSUE THREAD

**Issue by aisb459** [alphagov/govuk-frontend-docs#297]
Problem with 'Get started' (https://frontend.design-system.service.gov.uk/get-started/)

I am trying to use Govuk-Frontend npm package in Oracle JET Application. I have included the package in path_mapping.json and main.js. When I try to use them in js file I am getting an error saying "**Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'initAll')**" 
I have renamed all.js inside the package to govuk.js.

path_mapping.json =>
![image](https://user-images.githubusercontent.com/85751152/217011701-a3f723de-a5a0-4553-afcc-425eece33c1b.png)

main.js =>
![image](https://user-images.githubusercontent.com/85751152/217011994-49f20b53-231f-4ed9-a85b-5b331ff23fdb.png)

dashboard.js=>
![image](https://user-images.githubusercontent.com/85751152/217012326-6aacfd12-ce58-4259-aac8-eff90d10fcec.png)

Error=>
![image](https://user-images.githubusercontent.com/85751152/217012449-fce8affb-ce97-4354-b629-d36cad8bc0a4.png)

**Comment by owenatgov** [comment]
Hi @aisb459. Sorry for the delay in response. We've looked into this and have some suggestions for you to try:

1. We notice your app uses RequireJS. Looking at the guidance on [adding third-party tools](https://docs.oracle.com/en/middleware/developer-tools/jet/14/vdom/add-third-party-tools-or-libraries-your-oracle-jet-app.html) to a JET app, we would suggest following the `requirejs,config()` in your RequireJS bootstrap file approach
2. Avoid renaming `all.js` in `node_modules` as this will be renamed any time you run `npm install`
3. Remove the trailing `govuk` in your `cwd` path as you're then adding in another `govuk` in all your proceeding references so your app will be looking for `govuk-frontend/govuk/govuk/govuk`

I'm going to close this as we're not very familiar with Oracle JET and aren't able to provide capacity to interrogate this issue beyond what we've provided you so far.
