### ISSUE TITLE
Reporting on the usefulness of the content of the Localise GOV.UK Frontend page when modifying a component

### ISSUE THREAD

**Issue by wilsond-gds** [alphagov/govuk-frontend-docs#299]
Problem with 'Localise GOV.UK Frontend' (https://frontend.design-system.service.gov.uk/localise-govuk-frontend/)

Hello

I’ve been working on [adding the character count to a field in a form](https://github.com/alphagov/di-ipv-cri-dl-front/pull/83) which needed to be localised for 2 languages, English and Welsh. I found the localisation page reasonably quickly, but it took me a while to piece the information together I needed to get the code working.

Looking back on it now I think the `Changing text in the JavaScript for a component` content and the [section that shows how to do this with Nunjucks](https://frontend.design-system.service.gov.uk/localise-govuk-frontend/#understanding-pluralisation-rules:~:text=With%20Nunjucks,be%20our%20default%20%23%7D) could be closer together as they relate to the same part of the task? 

I also found it difficult to follow how I would create a `i18n` object and then put the e.g. `charactersUnderLimitText` string or object within that – that was the only way I could get this to work. Have I done this incorrectly, or does the Nunjucks example above need updating to the below? (it’s also possible that the particular set of technologies I'm using in the PR above requires the i18n strings to be passed in this way)

Hope that helps! Happy to discuss this further if you need any more information.

```
{{ govukCharacterCount({
  id: 'details',
  name: 'details',
  label: {
    html: 'Can you provide more details?'
  },
  maxlength: 1000,
 i18n:{
 charactersUnderLimitText: {
    other: '%{count} characters to go',
    one: 'One character to go'
  },
  charactersOverLimitText: {
    one: 'One character too many'
  }
},
}) }}
{# The `other` key for `characterOverLimitText` will be our default #}
```

**Comment by querkmachine** [comment]
Hi @wilsond-gds,

It looks like you've transposed some of the JavaScript syntax, which uses a parent `i18n` object, with the Nunjucks syntax, which doesn't. Removing that parent object should fix it.

```nunjucks
{{ govukCharacterCount({
  id: 'details',
  name: 'details',
  label: {
    html: 'Can you provide more details?'
  },
  maxlength: 1000,
  charactersUnderLimitText: {
    other: '%{count} characters to go',
    one: 'One character to go'
  },
  charactersOverLimitText: {
    one: 'One character too many'
  }
}) }}
```

The parameter names also slightly differ between them. e.g. It's `charactersUnderLimit` in the JS configuration, but `charactersUnderLimitText` in Nunjucks.

**Comment by claireashworth** [comment]
Hi @wilsond-gds,
Thank you for your input. I've been looking at this from a content perspective. At present I don't think it would be beneficial to split up the pluralisation examples, but I will look into ways to better sign post them so they're quicker to find. I'll also investigate whether including examples more often throughout the text would be useful.

**Comment by wilsond-gds** [comment]
Thanks for your responses: sorry I hadn't noticed them before now (need to work on a better triage system for my emails). I'll revisit this when I'm back from holiday next week.

**Comment by stevenjmesser** [comment]
Hi @wilsond-gds, did you have a chance to look at this?

**Comment by claireashworth** [comment]
Closing for now, but can reopen or start a new card as needed.
