### ISSUE TITLE
Update installation instruction to reflect new JavaScript loading strategy

### ISSUE THREAD

**Issue by romaricpascal** [alphagov/govuk-frontend-docs#308]
## What

Update the [Get started](https://frontend.design-system.service.gov.uk/get-started/#5-get-the-javascript-working) and [Import CSS, assets and JavaScript](https://frontend.design-system.service.gov.uk/importing-css-assets-and-javascript/#javascript) section to reflect our new way to load JavaScript.

## Why

We're [changing our recommendations for loading our JavaScript](https://github.com/alphagov/govuk-frontend/issues/2639)
and we need to communicate to users how we intend JavaScript to be loaded to ensure they can update their projects accordingly.

## Who needs to know about this

Developers

## Done when

```[tasklist]
- [ ] https://github.com/alphagov/govuk-frontend-docs/issues/203
- [x] Update (draft) Frontend Docs "Get the JavaScript working" to swap `all.js` with ES modules
- [x] Update (draft) Frontend Docs "Import CSS, assets and JavaScript" to swap `all.js` with ES modules
```

**Comment by colinrotherham** [comment]
Forgot this one is still in review:

* https://github.com/alphagov/govuk-frontend-docs/issues/203

**Comment by romaricpascal** [comment]
Moving to "Blocked" as the PRs have been reviewed but are held by other technical PRs (https://github.com/alphagov/govuk-frontend-docs/pull/318, https://github.com/alphagov/govuk-frontend-docs/pull/336 and https://github.com/alphagov/govuk-frontend-docs/pull/335)  they depend on before they can be merged into release/5.0 ultimately.

**Comment by colinrotherham** [comment]
Do we have to block this? I'm happy reviewing documentation knowing it's going into a queue

**Comment by colinrotherham** [comment]
Going to move back into **Needs review**

If you find anything held up let me know, I'll re-order the PRs

**Comment by colinrotherham** [comment]
Closing as we've now [completed those PRs](https://github.com/alphagov/govuk-frontend-docs/issues/308#issuecomment-1634443716) and we have [duplicate CSP hash tasks](https://github.com/alphagov/govuk-frontend/issues/3508)
