### ISSUE TITLE
Define and create new content needed for v5.0.0 of GOV.UK Frontend

### ISSUE THREAD

**Issue by claireashworth** [alphagov/govuk-frontend-docs#311]
## What
Define what changes are needed to update our content for v.5.0.0 of GOV.UK Frontend and draft content.

## Why
v5.0.0 might need explicit documentation to differentiate it from v4.0.0.

## Who needs to work on this and review it
Tech writer, content designer, developers, designers

## Done when
The content is agreed and drafted ready for testing with users and reviewing.

- [x] Use plans from [#3549](https://github.com/alphagov/govuk-frontend/issues/3549) to define what needs to be in documentation for v5.0.0
- [x] Write draft documentation for v5.0.0
- [x] Review complete
- [x] Final amendments before publishing

**Comment by claireashworth** [comment]
Content changes identified to date:

</div></b>Frontend Site

[Landing page](https://frontend.design-system.service.gov.uk/)

- clarify the line ‘use GOV.UK Frontend with old (‘legacy’) GOV.UK frameworks’
- add another line about using previous versions of frontend
- potentially move some of the initial ‘get started’ info to this page in preparation for amending that section (maybe a name change to something like ‘Setting up GOV.UK Frontend’)
[Install with Node.js package manager (npm)](https://frontend.design-system.service.gov.uk/installing-with-npm/)
- check whether the requirements need updating
- check whether the install instructions need updating
[Install using precompiled files](https://frontend.design-system.service.gov.uk/install-using-precompiled-files/)
- check whether package install is correct and update link as needed
- update the ‘cannot do after installing’ information. This could potentially include some relevant info about v4/v5 differences with a link to a new page on the differences if we go that route
- [from Ollie] update the example HTML to update the inline script and to remove the IE8 specific stylesheet
- [from Ollie] update the example in step 3 of ‘copy the files’ to remove the crown png reference
- [from Ollie] - In Get started step 5 ('Get the JavaScript working') - the inline script in step 1 will need updating and Step 3 will need updating (to use type="module", I think?)
[Update using Node.js package manager (npm](https://frontend.design-system.service.gov.uk/updating-with-npm/#update-using-node-js-package-manager-npm))
- update example where it shows version “4.5.0”
- update earlier versions example?
- would this work better if moved next to the Installing npm section?
[Support Internet Explorer 8](https://frontend.design-system.service.gov.uk/supporting-ie8/)
- [from Ollie] - This page will need to be removed
[Use with our old frameworks or colours](https://frontend.design-system.service.gov.uk/compatibility-mode/)
- [from Ollie] - This page will need to be removed
[Using HTML test files](https://frontend.design-system.service.gov.uk/testing-your-html/#using-the-html-test-files)
- Check if the file structure change means this section needs updating with different file paths
[Migration from our old frameworks](https://frontend.design-system.service.gov.uk/migrating-from-legacy-products/)
- [from Ollie] - This page will need to be removed
- This page to be replaced with a new page about migrating to v5 and highlighting the differences between v4 and v5 for reference
[Import CSS, assets and JavaScript](https://frontend.design-system.service.gov.uk/importing-css-assets-and-javascript/)
- [from Ollie] 'Import JavaScript using a bundler' might change
- [from Ollie] The CSP hash for the inline script will have changed in v5
- [from Ollie] 'Select and initialise an individual component' might change if we create a static function to instantiate new components
[Configure components with JavaScript](https://frontend.design-system.service.gov.uk/configure-components-with-javascript/)
- [from Ollie] 'Passing configuration to a new instance of a component in JavaScript' might change if we create a static function to instantiate new component
[Javascript API reference](https://frontend.design-system.service.gov.uk/javascript-api-reference/)
- [from Ollie] The example at the top of the document (set the preventDoubleClick option of a button) might change
[Sass API reference](https://frontend.design-system.service.gov.uk/sass-api-reference/)
- [from Ollie] The entry for $govuk-new-link-styles will no longer exist after v5, but needs to remain for v4

**Comment by claireashworth** [comment]
The 2 main pieces of content left to do are:

- the new page recorded in issue #315 (which will probably be completed in a separate PR)
- the 'undecided' elements discussed with the developers

**Comment by Izabela-16** [comment]
Ollie to look at documenting it on Friday, so Claire is clear what solution will be used.
