### ISSUE TITLE
Make it possible for users to navigate between different versions of the docs

### ISSUE THREAD

**Issue by stevenjmesser** [alphagov/govuk-frontend-docs#313]
## Context

We'll be hosting two versions of the docs – v4 and v5 – simultaneously for a year. 

## What

Make it possible for users to navigate between two versions of the docs, so that they can use the docs relevant to which version of GOV.‌UK Frontend they're using.

### Possible solutions

- Nest two folders inside the main directory, one for each version (e.g. `/v4/` and `/v5/`; Prototype Kit team do this)
- Use a navigation component to navigate between the two versions, e.g. see top-left of the [Tailwind CSS docs](https://tailwindcss.com/docs/installation)

## Who needs to know about this

Tech writer/content designer, developers, interaction designer, product/delivery manager.

**Comment by christopherthomasdesign** [comment]
I'd say that an interaction designer probs needs to have a look at this too – happy to help

**Comment by stevenjmesser** [comment]
Good point! Have amended the description.

**Comment by 36degrees** [comment]
I think this is done.
