### ISSUE TITLE
Add guidance on staying up to date

### ISSUE THREAD

**Issue by 36degrees** [alphagov/govuk-frontend-docs#339]
## What

Replace the [existing guidance on updating with npm](https://frontend.design-system.service.gov.uk/updating-with-npm/) with new guidance that covers:

- the benefits of staying up to date
- how to find out what version you are currently using
- how to update if you've installed GOV.UK Frontend from precompiled files
- how to be notified when there's a new release (replacing [the existing guidance in the README](https://github.com/alphagov/govuk-frontend#getting-updates))
- how versioning works
- how to use the release notes effectively (for example what each of the sections mean)

Then:

- redirect the old path for the updating with npm guidance to the new docs
- replace the section in the README with a link to the docs
- add a link from the top of the changelog to the new guidance

## Why

We want to encourage all users – not just those who have installed from npm – to keep up to date with new releases.

We want to be able to link from the release notes to some supporting material that helps users understand how to use them effectively.

## Who needs to know about this

Tech writer, developers

## Done when

- [ ] New guidance on staying up to date has been published
- [ ] README updated to remove duplication and link to the new guidance
- [x] The existing URL for the updating with npm guidance redirects to the new guidance

**Comment by 36degrees** [comment]
Waiting for external 2i.

**Comment by claireashworth** [comment]
external 2i complete in google doc.
