### ISSUE TITLE
Add guidance on graded browser support

### ISSUE THREAD

**Issue by claireashworth** [alphagov/govuk-frontend-docs#340]
## What
Add a new page on how the team will provide graded browser support.

## Why
As part of v5 the team is stopping or reducing support for older browsers.

## Who needs to know about this
Tech writer, developers

## Done when

- [ ] new page is drafted, reviewed and published
- [ ] new page has links between other related guidance

**Comment by claireashworth** [comment]
Link to [draft document](https://docs.google.com/document/d/1U5yQPYkomtPsLx3rPoNRrF9Kbei8KsIfnOSEUPMfbpM/edit?usp=sharing)

**Comment by claireashworth** [comment]
Re-shared document with team for review

**Comment by claireashworth** [comment]
Team has reviewed. There is one change left for approval about Safari versions supported in which assigned browser grade. There are no 2 docs. a shorter doc for the frontend site and a more detailed doc to go onto GitHub.
Another tech writer or content designer should give it a quick review as well before we add it to the final release. Review not needed for the pre-release as we might get comments back and need to make changes.

**Comment by claireashworth** [comment]
Added Ollie and Romaric for final review on:

[Browser support - short version](https://docs.google.com/document/d/10rkRaoPo_1nVw1hmYSSUKEttBKrY9OSM-6bI-5J5QJ4/edit?usp=sharing)
[Browser support (full version)](https://docs.google.com/document/d/1U5yQPYkomtPsLx3rPoNRrF9Kbei8KsIfnOSEUPMfbpM/edit?usp=sharing)

Publishing the short version. Page list as follows:
Get started
NEW PAGE - Stay up to date with the latest Frontend changes (published)
NEW PAGE - Changes to GOV.UK Frontend v5.0.0 ([#315](https://github.com/alphagov/govuk-frontend-docs/issues/315))
NEW PAGE - How we provide support for different browsers (short version)

Publishing the full version:
Add to repo - docs/contributing/browser-support.md

**Comment by romaricpascal** [comment]
Closed by #356 and alphagov/govuk-frontend#4381
