### ISSUE TITLE
Spike technical approach for hosting v4 in a subfolder

### ISSUE THREAD

**Issue by romaricpascal** [alphagov/govuk-frontend-docs#346]
## What

Explore the impacts of hosting v4 in a subfolder, especially:
- links (eg. [moving to relative links](https://github.com/alphagov/govuk-prototype-kit-docs/pull/84), it might be worth thinking at some linting there as well)
- making the frontend-docs menu work with two sets of documentation (we may want to look into what [publishing docs](https://docs.publishing.service.gov.uk/manual/get-started.html) are doing)
- having a way to navigate between v4 and v5 docs (similarly, looking at publishing docs may be a good start, but we may want to anticipate how to look at more than 2 versions for future upates when we expand our public API, for ex).

## Why

We need to validate the feasibility of our plan for hosting older version of frontend-docs in sub folders

## Who needs to know about this

Developers

## Done when

- [ ] We've listed the constraints hosting v4 in a subfolder raises
- [ ] We have a plan to work with each of these constraints

**Comment by 36degrees** [comment]
I've had a go at spiking this to see what the problems are. It all feels a little bit hacky, but I've managed to get 90% of the way there pretty quickly:

- [Spike branch](https://github.com/alphagov/govuk-frontend-docs/compare/release/5.0...v4-docs-folder?expand=1)
- [Preview](https://v4-docs-folder--govuk-frontend-docs-preview.netlify.app/)

The main 'unsolved' problems are:

- When building the table of contents for the v4 section, `v4/index.html` is seen as a parent of all the other files, which means the nav is generated very differently for the 2 sections
- The v4 docs are also included at the very bottom of the v5 sidebar
- The v5.x link in the header isn’t highlighted when on subpages for v5

I've found it useful to see how [GOV.UK Publishing Developer Docs](https://github.com/alphagov/govuk-developer-docs) have done things (the most complex use of the tech-docs-gem I'm aware of). For example, they have a separate ['multipage layout'](https://github.com/alphagov/govuk-developer-docs/blob/main/source/layouts/multipage_layout.html.erb) that got me 90% of the way there for rendering the v4 sidebar.

I think if we needed to we could consider just hard-coding the v4 nav and ignoring the missing highlight of 'v5.x' to get this out the door, but worth trying to tidy a few bits up.

The tech docs gem doesn't really have an owner but it'd be worth thinking about what it'd take to get this supported in a less hacky way.

I'm not sure if I'll get a chance to come back to this before I go on leave, so if anyone else wants to pick this up then please do.

**Comment by romaricpascal** [comment]
Open a clean PR based on the spike branch, we can iterate the search if necessary if feedback comes in.

**Comment by romaricpascal** [comment]
Implemented in https://github.com/alphagov/govuk-frontend-docs/pull/384 🥳
