### ISSUE TITLE
Update the V5 release content based on feedback from research

### ISSUE THREAD

**Issue by claireashworth** [alphagov/govuk-frontend-docs#366]
## What

Update the 'Changes to V5' page based on feedback from research.
This includes:

* potentially moving the page to the top of the side bar
* making sure all the links are going to the correct version of Frontend
* adding a section on benefits of migrating to V5

## Why

These improvements will help users find and use the information they need to migrate to V5.

## Who needs to write and review

Tech writer, Developer

## Done when

* \[x] Agree on the changes to make
* \[x] Draft changes
* \[x] Team review and approve
* \[x] 2i review from another tech writer or content designer

### Tasks
- \[x] Move the page 'Changes to V5' to the top of the side bar
- \[ ] https://github.com/alphagov/govuk-frontend-docs/issues/368
- \[x] Check all links are going to the correct version of frontend
- \[ ] https://github.com/alphagov/govuk-frontend-docs/issues/367
- \[x] Add more information on graded browser support to 'changes to V5' and potentially the release notes and add links to guidance
- \[ ] https://github.com/alphagov/govuk-frontend-docs/issues/393
- \[ ] https://github.com/alphagov/govuk-frontend-docs/issues/376
- \[ ] https://github.com/alphagov/govuk-frontend-docs/issues/372
- \[ ] https://github.com/alphagov/govuk-frontend-docs/issues/377
- \[ ] https://github.com/alphagov/govuk-frontend-docs/issues/370
- \[ ] https://github.com/alphagov/govuk-frontend-docs/issues/369
- \[ ] https://github.com/alphagov/govuk-frontend-docs/issues/371
- \[ ] https://github.com/alphagov/govuk-frontend-docs/issues/373
- \[ ] https://github.com/alphagov/govuk-frontend-docs/issues/374
- \[ ] https://github.com/alphagov/govuk-frontend-docs/issues/375
- \[ ] https://github.com/alphagov/govuk-frontend-docs/issues/378
- \[ ] https://github.com/alphagov/govuk-frontend-docs/issues/379
- \[ ] https://github.com/alphagov/govuk-frontend-docs/issues/380

**Comment by romaricpascal** [comment]
All done 🥳
