### ISSUE TITLE
Mention browser support earlier the release notes

### ISSUE THREAD

**Issue by romaricpascal** [alphagov/govuk-frontend-docs#369]
## What

- Make sure we mention browser support early on so people can quickly decide whether it’s for them or not
- Mention that our decision of dropping IE relies on expecting services to use progressive enhancements
- Explain the use of `type="module"` to help not run scripts in browsers where GOV.UK Frontend is not supported 
- Clarify that we’re dropping IE support for JavaScript only and that our CSS still works for IE11

## Why

Our decision to drop IE support for JavaScript is one of the big changes of v5 and it needs to appear clearly and early so services can quickly know to assess its impact on their implementation

## Who needs to work on this

Developers, Tech writers

## Who needs to review this

Developers, Tech writers

## Done when

- [ ] The release notes have a clear section, quite high up, mentioning our browser support for JavaScript

**Comment by claireashworth** [comment]
Browser support and progressive enhancement are mentioned in the summary with links to pages with more info. Dropping JS only for IE11 is clarified.
Only the ES module to clarify.

**Comment by romaricpascal** [comment]
Updated in the [draft changelog (internal)](https://docs.google.com/document/d/1NYOSJBI4ClFCRoATjn8bfLcSTWgnfrXLhpNTdu7Fdz8/edit#heading=h.o9e6e57cine3)
