### ISSUE TITLE
Clarify on the 'graded browser support' page that the removal of IE11 support is for JavaScript only

### ISSUE THREAD

**Issue by romaricpascal** [alphagov/govuk-frontend-docs#370]
## What

Clarify on the 'graded browser support' page that the removal of IE11 support is for JavaScript only.
[Link to draft doc.](https://docs.google.com/document/d/1U5yQPYkomtPsLx3rPoNRrF9Kbei8KsIfnOSEUPMfbpM/edit?usp=sharing)

## Why

We haven't dropped support for IE wholesale, we still support IE11 for our CSS.

## Who needs to work on this

Developers, Tech writers

## Who needs to review this

Developers, Tech writers

## Done when

- [ ] The 'graded browser support' page makes it clear what we've stopped supporting on IE11

**Comment by claireashworth** [comment]
I've included an amended line from the release notes about removal of IE11 support for the JS only. We will need to remove or change this line when v5 is more established.

**Comment by romaricpascal** [comment]
[Google doc (internal)](https://docs.google.com/document/d/1U5yQPYkomtPsLx3rPoNRrF9Kbei8KsIfnOSEUPMfbpM/edit)
