### ISSUE TITLE
Reorder the content in the release notes to take into account importance of actions and dependencies (breaking changes first, then new features)

### ISSUE THREAD

**Issue by romaricpascal** [alphagov/govuk-frontend-docs#376]
## What

Reorder the content in the release notes to take into account importance of actions and dependencies (breaking changes first, then new features)

## Why

Helps put first what’s actually necessary to get the New features
Would be familiar with how other tools like Dependabot advertise breaking changes

## Who needs to work on this

Developers, Tech writers

## Who needs to review this

Developers, Tech writers

## Done when

- [ ] Release notes have been re-ordered to account for importance of actions and dependencies

**Comment by claireashworth** [comment]
Release notes have had some reordering but need to check if anything else needs shuffling around.

**Comment by romaricpascal** [comment]
Updated in the [draft changelog (internal)](https://docs.google.com/document/d/1NYOSJBI4ClFCRoATjn8bfLcSTWgnfrXLhpNTdu7Fdz8/edit#heading=h.o9e6e57cine3)
