### ISSUE TITLE
Add an intro summary to release notes listing the links users need and the main changes they need to make

### ISSUE THREAD

**Issue by romaricpascal** [alphagov/govuk-frontend-docs#377]
## What

Add an intro summary to release notes listing the links users need and the main changes they need to make

Link to [draft doc (internal)](https://docs.google.com/document/d/1NYOSJBI4ClFCRoATjn8bfLcSTWgnfrXLhpNTdu7Fdz8/edit?usp=sharing)

## Why

Help users quickly understand the changes they might need to make and what they get from the release

## Who needs to work on this

Developers, Tech writers

## Who needs to review this

Developers, Tech writers

## Done when

- [ ] The release notes have a summary of the release updates

**Comment by claireashworth** [comment]
Draft intro summary is done. Review is scheduled for Monday.
