### ISSUE TITLE
Reference compatibility mode mixin with its full name in the release notes

### ISSUE THREAD

**Issue by romaricpascal** [alphagov/govuk-frontend-docs#379]
## What

Reference the `govuk-compatibility-mode` mixin with its full name, rather than just `compatibility-mode` (within '"Compatibility mode" features are no longer supported')

## Why

This will help users search their codebase for the use of that mixin without risk of collision with another piece of code that's named `< SOMETHING >compatibility-mode< SOMETHING>`.

## Who needs to work on this

Developers, Tech writers

## Who needs to review this

Developers, Tech writers

## Done when

- [x] The mixin is referenced by its correct name
- [ ] We've checked if other naming mishapps are in the release notes

**Comment by 36degrees** [comment]
Added a suggestion in the doc that resolves this

**Comment by romaricpascal** [comment]
Updated in the [draft changelog (internal)](https://docs.google.com/document/d/1NYOSJBI4ClFCRoATjn8bfLcSTWgnfrXLhpNTdu7Fdz8/edit#heading=h.o9e6e57cine3)
