### ISSUE TITLE
Encourage only including code for things that are being used

### ISSUE THREAD

**Issue by 36degrees** [alphagov/govuk-frontend-docs#436]
## What
Amend the content in selected pages of the Frontend site to make the user installation journey clearer including only using the code you need. 

## How
Remove or move pages that are no longer needed in their current location
Update headings and content of remaining pages focusing on clarity and de-duplication of information

## Who
Tech writer, Developers

**Comment by claireashworth** [comment]
Proposal for changes written and shared with team for review.

**Comment by claireashworth** [comment]
Team review complete. Drafting changes underway.
