### ISSUE TITLE
Include default values for settings in the Sass API reference

### ISSUE THREAD

**Issue by 36degrees** [alphagov/govuk-frontend-docs#45]
## What

Document the default values for settings within the Sass API reference

## Why

As a user configuring GOV.UK Frontend, knowing what the default value for a setting is helps me understand how that setting is used, and whether I need to change it.

**Comment by 36degrees** [comment]
@m-green any thoughts on the best way to add this?

The [previous Sass documentation shows the variable as it's defined in the code](http://govuk-frontend-review.herokuapp.com/docs/#settings/colours-variable-govuk-brand-colour), for example:

> ## govuk-brand-colour
> 
> ```scss
> $govuk-brand-colour: govuk-colour("blue") !default;
> ```
> ### Description
> Brand colour
> 
> ### Type
> Colour

At the minute, in the Frontend docs, we just have:

> ## $govuk-brand-colour
> Brand colour
>
> View source code for _colours-applied.scss on GitHub

**Comment by m-green** [comment]
Ah good spot! I have to admit I found the old style a little confusing - it wasn't necessarily clear whether the code was a default, a usage example, or something else. 

As a quick fix, would it be possible to bring them back but add an h4 above them to clarify what they are? Something like 'Default in GOV.UK Frontend'.  

Longer-term, we should aim to have a 'usage' example for each setting.
