### ISSUE TITLE
Mark LibSass as deprecated in 'Installing with npm' documentation

### ISSUE THREAD

**Issue by 36degrees** [alphagov/govuk-frontend-docs#81]
## What

In '[Install with Node.js package manager (npm)](https://frontend.design-system.service.gov.uk/installing-with-npm/#requirements)' we say:

> Install either:
> 
> - LibSass - version 3.3.0 or higher
> - Dart Sass - version 1.0.0 or higher
> 
> GOV.UK Frontend also works with Ruby Sass version 3.4.0 or higher, but we recommend you do not use Ruby Sass because it’s been deprecated.

Since writing this, LibSass has now [also been deprecated](https://github.com/sass/sassc/issues/273):

> All of this means that it's time to start directing users away from LibSass, standardizing on Dart Sass as the primary (and for now the only) recommended language implementation.

We should update our own documentation to prefer Dart Sass over the two deprecated libraries. We will still continue to fully support LibSass for a while yet (likely until we [migrate to the Sass module system](https://github.com/alphagov/govuk-frontend/issues/1791)), in the same way we continue to support Ruby Sass.

## Why

For new projects it makes sense to recommend Dart Sass over the other implementations wherever possible, especially as we intend to migrate to the Sass module system at some point in the future, which currently would require users to migrate to Dart Sass.

## Done when…

- [x] Guidance drafted to recommend Dart Sass over the deprecated LibSass and Ruby Sass libraries, whilst making it clear that the deprecated libraries are still supported _for the time being_
- [x] Guidance 2i'ed
- [x] Updated guidance published

**Comment by EoinShaughnessy** [comment]
Have drafted changes and shared PR with Olly for review: https://github.com/alphagov/govuk-frontend-docs/pull/82

**Comment by EoinShaughnessy** [comment]
@36degrees Steve Evans has 2i'd and approved this update, and I've merged it: https://github.com/alphagov/govuk-frontend-docs/pull/82

When does the update become visible on https://deploy-preview-83--govuk-frontend-docs-preview.netlify.app/get-started/#4-get-the-font-and-images-working?
